/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Enterobius_H.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
  animations: GLTFAction[]
}

/**
 * @description Componente 3D para el huevo de Enterobius vermicularis (Oxiuro).
 * @param props Propiedades de grupo de Three.js para posicionamiento en el canvas.
 */
export function EnterobiusH(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/models/enterobius-vermicularis_H.glb') as unknown as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={nodes.mesh_0.material} 
        name="enterobius_egg_mesh"
      />
    </group>
  )
}

useGLTF.preload('/models/enterobius-vermicularis_H.glb')