/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Enterobius_A.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

// Senior Note: Definimos el tipo para clips de animación por si el modelo los incluye.
type GLTFAction = THREE.AnimationClip

// Definimos la estructura exacta del resultado del GLTF
type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {
    // Si el modelo tiene materiales específicos, se pueden listar aquí.
    [key: string]: THREE.Material
  }
  animations: GLTFAction[]
}

/**
 * @description Componente 3D para el espécimen adulto de Enterobius vermicularis (Oxiuro).
 * @param props Propiedades de grupo de Three.js, permitiendo posicionamiento y eventos.
 */
export function EnterobiusA(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/models/enterobius-vermicularis_A.glb') as unknown as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={nodes.mesh_0.material} 
        name="enterobius_adult_mesh"
      />
    </group>
  )
}

useGLTF.preload('/models/enterobius-vermicularis_A.glb')