/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Giardia_A.glb 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ThreeElements } from '@react-three/fiber';

type GLTFAction = THREE.AnimationClip;

// Definimos la interfaz estricta basada en la estructura del modelo Giardia duodenalis.
type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {
    [key: string]: THREE.Material;
  };
  animations: GLTFAction[];
};

/**
 * @description Componente 3D para el trofozoíto de Giardia duodenalis.
 * @param props Propiedades de grupo de Three.js (posición, escala, rotación).
 */
export function GiardiaA(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/3d_models/giardia-duodenalis_A.glb') as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        name="giardia_trophozoite_mesh"
      />
    </group>
  );
}

useGLTF.preload('/3d_models/giardia-duodenalis_A.glb');
