/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Giardia_H.glb 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFAction = THREE.AnimationClip

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
  animations: GLTFAction[]
}

export function GiardiaH(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/models/giardia-duodenalis_H.glb') as unknown as GLTFResult
  
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.mesh_0.geometry} 
        material={nodes.mesh_0.material} 
        name="giardia_egg_mesh"
      />
    </group>
  )
}

useGLTF.preload('/models/giardia-duodenalis_H.glb')