/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Necator_A.glb 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ThreeElements } from '@react-three/fiber';

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  animations: GLTFAction[];
};

export function NecatorA(props: ThreeElements['group']) {
  const { nodes } = useGLTF('/3d_models/necator-americanus_A.glb') as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        name="necator_adult_mesh"
      />
    </group>
  );
}

useGLTF.preload('/3d_models/necator-americanus_A.glb');
